**Welcome to Numpy Tutorial,Lets do it**


In [1]:
import numpy as np

In [2]:
myarr=np.array([1,2,3])

In [3]:
myarr

array([1, 2, 3])

In [4]:
myarr.shape

(3,)

In [5]:
myarr[0]

1

In [6]:
myarr[1]

2

In [7]:
myarr.dtype

dtype('int32')

In [8]:
myarr[0]=2

In [9]:
myarr

array([2, 2, 3])

**Array Creation :from other Python Structures**

In [10]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
listarray


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
rng=np.arange(15)

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
range=np.arange(12)

In [18]:
range


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
lspace=np.linspace(1,5,12)

In [21]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [22]:
ide=np.identity(20)

In [23]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [24]:
ide.shape

(20, 20)

In [25]:
range=np.arange(99)

In [28]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
range.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
range.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
range=np.arange(100)

In [36]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
range.reshape(2,50)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [38]:
range.shape

(100,)

In [39]:
range.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
range.shape

(100,)

In [41]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [42]:
arr=np.array(x)

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
arr.sum(axis=0)

array([12,  8,  9])

In [45]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [46]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [48]:
arr.flat

In [50]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [52]:
arr.size

9

In [53]:
arr.ndim

2

In [54]:
arr.nbytes

36

In [55]:
ar=np.array([1,3,4,634,2])

In [57]:
ar

array([  1,   3,   4, 634,   2])

In [58]:
ar.argmax()

3

In [59]:
ar.argmin()

0

In [60]:
ar.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [61]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [62]:
arr.argmax()

6

In [63]:
arr.argmin()

8

In [65]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [66]:
arr.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [67]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [68]:
arr.shape

(3, 3)

In [69]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
arr2=np.array([[1,0,2],[2,3,1],[1,2,0]])

In [71]:
arr2


array([[1, 0, 2],
       [2, 3, 1],
       [1, 2, 0]])

In [72]:
arr+arr2

array([[2, 2, 5],
       [6, 8, 7],
       [8, 3, 0]])

In [73]:
arr*arr2

array([[ 1,  0,  6],
       [ 8, 15,  6],
       [ 7,  2,  0]])

In [75]:
arr.sum()

29